services:
    caddy:
        image: docker.io/library/caddy:2.9.1
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - caddy_caddy_data:/data
            - caddy_config:/config
            - $HOME/data/archive.observer:/aharc
            - $HOME/logs/caddy:/logs
        networks:
            - caddy_default
        secrets:
            - guest-password-hash
            - private-password-hash
        environment:
            GUEST_PASSWORD_HASH_FILE: /run/secrets/guest-password-hash
            PRIVATE_PASSWORD_HASH_FILE: /run/secrets/private-password-hash
        # environment:
        # HETZNER_DNS_API_KEY: "${HETZNER_DNS_API_KEY}"
        # network_mode: "slirp4netns:port_handler=slirp4netns"

        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 50MB

volumes:
    caddy_caddy_data:
        external: true
    caddy_config:

networks:
    caddy_default:
        external: true
        name: caddy_default

secrets:
    guest-password-hash:
        file: ./guest-password-hash-secret
    private-password-hash:
        file: ./private-password-hash-secret
