version: "3.7"

services:
    caddy:
        image: docker.io/library/caddy:2.6.4
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - $PWD/Caddyfile:/etc/caddy/Caddyfile
            - caddy_caddy_data:/data
            - caddy_config:/config
            - $HOME/data/aharc:/aharc
        # environment:
        # HETZNER_DNS_API_KEY: "${HETZNER_DNS_API_KEY}"
        # network_mode: "slirp4netns:port_handler=slirp4netns"

volumes:
    caddy_caddy_data:
        external: true
    caddy_config:
