services:
    linkblocks:
        image: ghcr.io/raffomania/linkblocks:latest
        networks:
            - caddy_proxy
            - default
        depends_on:
            db:
                condition: service_healthy
        environment:
            - LISTEN=0.0.0.0:3000
            - DATABASE_NAME=linkblocks
            - DATABASE_URL=postgres://linkblocks:linkblocks@db/linkblocks
            - BASE_URL=https://lb.zwielich.tech
            - RUST_LOG=linkblocks=debug,tower_http=debug,tower_http::trace::on_request=info,axum::rejection=trace,sqlx=debug
        restart: always

        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 64MB
    db:
        image: docker.io/library/postgres:17.2-alpine
        environment:
            - POSTGRES_DB=linkblocks
            - POSTGRES_USER=linkblocks
            - POSTGRES_PASSWORD=linkblocks
        volumes:
            - db:/var/lib/postgresql/data
        command: |
            -c shared_buffers=16MB 
            -c work_mem=1MB 
            -c max_connections=10 
            -c maintenance_work_mem=4MB 
            -c effective_cache_size=32MB
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 64MB

        healthcheck:
            test: ["CMD", "pg_isready", "-U", "linkblocks"]
            interval: 60s
            start_period: 30s
        restart: always

volumes:
    db:
        # Name is from quadlet times
        name: systemd-linkblocks-postgres

networks:
    caddy_proxy:
        external: true
        name: caddy_default
    default:
