services:
    metube:
        image: ghcr.io/alexta69/metube:2024-07-17
        container_name: metube
        restart: unless-stopped
        environment:
            - DELETE_FILE_ON_TRASHCAN=true
        ports:
            - "8081:8081"
        volumes:
            - downloads:/downloads
        networks:
            - caddy_proxy

volumes:
    downloads:

networks:
    caddy_proxy:
        external: true
        name: caddy_default
