services:
    spc_signup:
        restart: always
        volumes:
            - $HOME/spc-signup:/spc-signup
        working_dir: /spc-signup
        command: bun run index.ts
        env_file: .env
        networks:
            - caddy_proxy
        build:
            context: $HOME/spc-signup
            dockerfile: Containerfile

networks:
    caddy_proxy:
        external: true
        name: caddy_default
