version: "3.7"

services:
    spc_signup:
        restart: always
        volumes:
            - $HOME/spc-signup:/spc-signup
        working_dir: /spc-signup
        command: bun run index.ts
        networks:
            - caddy_proxy
        build: $HOME/spc-signup

networks:
    caddy_proxy:
        external:
            name: caddy_default
