services:
    actual:
        image: docker.io/actualbudget/actual-server:25.3.1-alpine
        networks:
            - caddy_proxy
        environment:
            - ACTUAL_PORT=3000
        volumes:
            - data:/data
        restart: always

        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100MB

volumes:
    data:

networks:
    caddy_proxy:
        external: true
        name: caddy_default
