services:
    actual:
        image: docker.io/actualbudget/actual-server:24.5.0-alpine
        networks:
            - caddy_proxy
        environment:
            - ACTUAL_PORT=3000
        volumes:
            - actual-data:/data
        restart: always

volumes:
    actual-data:

networks:
    caddy_proxy:
        external: true
        name: caddy_default
