services:
    miniflux:
        image: docker.io/miniflux/miniflux:2.2.5
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
            - PORT=8080
            - RUN_MIGRATIONS=1
            - CREATE_ADMIN=1
            - ADMIN_USERNAME=rafael
            - ADMIN_PASSWORD=changeme
            # - DATABASE_URL_FILE=/run/secrets/miniflux_database_url
            # - ADMIN_USERNAME_FILE=/run/secrets/miniflux_admin_username
            # - ADMIN_PASSWORD_FILE=/run/secrets/miniflux_admin_password
        networks:
            - caddy_proxy
            - default
        healthcheck:
            test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
        restart: always

        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 100MB
    db:
        image: docker.io/library/postgres:17.2
        environment:
            - POSTGRES_USER=miniflux
            - POSTGRES_PASSWORD=secret
            # - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        volumes:
            - miniflux-db:/var/lib/postgresql/data
        command: |
            -c shared_buffers=16MB 
            -c work_mem=1MB 
            -c max_connections=10 
            -c maintenance_work_mem=4MB 
            -c effective_cache_size=32MB
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "miniflux"]
            interval: 60s
            start_period: 30s
        restart: always

        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: 64MB
volumes:
    miniflux-db:
# secrets:
#     miniflux_database_url:
#         external: true

#     miniflux_admin_username:
#         external: true

#     miniflux_admin_password:
#         external: true

#     postgres_password:
#         external: true

networks:
    caddy_proxy:
        external: true
        name: caddy_default
    default:
